### ISSUE TITLE
Installing gem on High Sierra fails

### ISSUE THREAD

**Issue by webflo** [boxen/puppet-ruby#157]
Installing gems via boxen fails on High Sierra.

```
Debug: Executing with uid=fweber: '/opt/rubies/2.1/bin/gem install 'bundler' --version '1.16.0' --source 'https://rubygems.org/' --no-rdoc --no-ri --verbose'
Error: Execution of '/opt/rubies/2.1/bin/gem install 'bundler' --version '1.16.0' --source 'https://rubygems.org/' --no-rdoc --no-ri --verbose' returned 1: /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rubies/2.1.9/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rubies/2.1.9/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util/execution.rb:235:in `execute'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/provider.rb:101:in `execute'
/opt/boxen/repo/shared/ruby/lib/puppet/provider/ruby_gem/rubygems.rb:122:in `execute'
/opt/boxen/repo/shared/ruby/lib/puppet/provider/ruby_gem/rubygems.rb:140:in `gem'
/opt/boxen/repo/shared/ruby/lib/puppet/provider/ruby_gem/rubygems.rb:95:in `block in create'
/opt/boxen/repo/shared/ruby/lib/puppet/provider/ruby_gem/rubygems.rb:94:in `each'
/opt/boxen/repo/shared/ruby/lib/puppet/provider/ruby_gem/rubygems.rb:94:in `create'
/opt/boxen/repo/shared/ruby/lib/puppet/type/ruby_gem.rb:6:in `block (3 levels) in <top (required)>'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/property.rb:487:in `set'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/property.rb:561:in `sync'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction/resource_harness.rb:236:in `sync'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction/resource_harness.rb:134:in `sync_if_needed'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction/resource_harness.rb:80:in `perform_changes'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction/resource_harness.rb:21:in `evaluate'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:230:in `apply'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:246:in `eval_resource'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:163:in `call'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:163:in `block (2 levels) in evaluate'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util.rb:507:in `block in thinmark'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util.rb:506:in `thinmark'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:163:in `block in evaluate'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction.rb:154:in `evaluate'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/resource/catalog.rb:222:in `block in apply'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util/log.rb:155:in `with_destination'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/transaction/report.rb:142:in `as_logging_destination'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/resource/catalog.rb:221:in `apply'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/configurer.rb:171:in `block in apply_catalog'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util.rb:224:in `block in benchmark'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util.rb:223:in `benchmark'
/opt/boxen/repo/shared/boxen/lib/puppet/provider/package/hax.rb:13:in `benchmark'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/configurer.rb:170:in `apply_catalog'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/configurer.rb:343:in `run_internal'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/configurer.rb:221:in `block in run'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/context.rb:65:in `override'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet.rb:306:in `override'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/configurer.rb:195:in `run'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application/apply.rb:350:in `apply_catalog'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application/apply.rb:274:in `block in main'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/context.rb:65:in `override'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet.rb:306:in `override'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application/apply.rb:225:in `main'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application/apply.rb:170:in `run_command'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application.rb:358:in `block in run'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util.rb:662:in `exit_on_fail'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/application.rb:358:in `run'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util/command_line.rb:132:in `run'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/lib/puppet/util/command_line.rb:72:in `execute'
/opt/boxen/repo/.bundle/ruby/2.3.0/gems/puppet-4.10.8-universal-darwin/bin/puppet:5:in `<top (required)>'
/opt/boxen/repo/bin/puppet:16:in `load'
/opt/boxen/repo/bin/puppet:16:in `<main>'
```

@jacobbednarz Do you have any idea how to resolve this? I am not very proficient in ruby. I don't understand why ruby 2.1.9 uses /Library/Ruby/Gems/2.3.0 as include path.

**Comment by webflo** [comment]
``rake-10.3.2`` is the version we use in boxen. I think the gem-setup from our-boxen leaks into the installation process? If i run the same command on my shell it works without any issues.

**Comment by webflo** [comment]
Resolved it with https://github.com/webflo/puppet-ruby/commit/c4416b17406ef5d82d3318d7aa384c3fd641de6e
